create or replace PROCEDURE HASHCODEVERIFY (p_code IN NUMBER, p_valid OUT NUMBER)
IS
code NUMBER;
BEGIN
SELECT HASHCODE INTO code FROM HASHTABLE
WHERE HASHCODE = p_code;
IF(sql%FOUND) THEN p_valid := 1;
END IF;
EXCEPTION
WHEN NO_DATA_FOUND THEN
p_valid := 0;
END;