create or replace PROCEDURE MASTERADMINLOGIN (p_username IN VARCHAR2, p_password IN VARCHAR2, p_valid OUT NUMBER)
IS
t_username VARCHAR2(20);
BEGIN
SELECT USERNAME INTO t_username FROM MASTERADMIN
WHERE USERNAME = p_username AND PASSWORD = p_password;
IF (sql%FOUND) THEN p_valid := 1;
END IF;
EXCEPTION
WHEN NO_DATA_FOUND THEN
p_valid := 0;
END;
