---ACCOUNT TABLE

CREATE TABLE  ACCOUNT 
   (	ACC_NO NUMBER, 
	BALANCE NUMBER(10,2) NOT NULL, 
	TYPE VARCHAR2(10) NOT NULL, 
	ACC_OPEN DATE NOT NULL, 
	CONSTRAINT PK_ACCCOUNT PRIMARY KEY (ACC_NO)
   );
   
   
---ACCOUNT INFORMATION TABLE

CREATE TABLE ACCOUNT_INFO
   (	ACC_NO NUMBER, 
	NAME VARCHAR2(20) NOT NULL, 
	MOBILE VARCHAR2(11) NOT NULL, 
	PRESENT_ADDRESS VARCHAR2(20) NOT NULL, 
	PERMANENT_ADDRESS VARCHAR2(20) NOT NULL, 
	USERNAME VARCHAR2(20) NOT NULL, 
	PASSWORD VARCHAR2(20) NOT NULL, 
	GENDER VARCHAR2(10) NOT NULL, 
	 CONSTRAINT PK_ACCOUNT_INFO PRIMARY KEY (ACC_NO), 
	 CONSTRAINT FK_ACCOUNT_INFO FOREIGN KEY (ACC_NO)
	  REFERENCES ACCOUNT (ACC_NO) ON DELETE CASCADE
   );
   
---HASHCODE TABLE

CREATE TABLE  HASHTABLE 
   (	ACC_NO NUMBER NOT NULL ENABLE, 
	AMOUNT NUMBER NOT NULL ENABLE, 
	TDATE DATE NOT NULL ENABLE, 
	HASHCODE NUMBER NOT NULL ENABLE
   );
   
---ADMIN LOGIN TABLE

CREATE TABLE  LOGIN 
   (	USERNAME VARCHAR2(20), 
	PASSWORD VARCHAR2(20) NOT NULL ENABLE, 
	NAME VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT PK_LOGIN PRIMARY KEY (USERNAME) ENABLE
   );
   
---MASTERADMIN LOGIN TABLE

CREATE TABLE  MASTERADMIN 
   (	USERNAME VARCHAR2(20) NOT NULL ENABLE, 
	PASSWORD VARCHAR2(20) NOT NULL ENABLE
   );
   
---TRANSACTION TABLE

CREATE TABLE  TRANSACTION 
   (	TRX_ID NUMBER(6,0), 
	ACC_NO NUMBER NOT NULL ENABLE, 
	TRX_DATE DATE NOT NULL ENABLE, 
	TRX_TIME VARCHAR2(20) NOT NULL ENABLE, 
	AMOUNT NUMBER NOT NULL ENABLE, 
	TRX_TYPE VARCHAR2(30) NOT NULL ENABLE, 
	TRX_ACCOUNT NUMBER, 
	 CONSTRAINT PK_TRANSACTION PRIMARY KEY (TRX_ID) ENABLE, 
	 CONSTRAINT FK_TRANSACTION FOREIGN KEY (ACC_NO)
	  REFERENCES  ACCOUNT (ACC_NO) ON DELETE CASCADE ENABLE
   );
   
   

