---ACCOUNT ID GENERATOR

CREATE OR REPLACE TRIGGER  TRIGG1
BEFORE INSERT ON ACCOUNT FOR EACH ROW
BEGIN
:new.ACC_NO := generate_acc_id;
END;

---TRANSACTION ID GENERATOR

CREATE OR REPLACE TRIGGER  TRIG_TRX
BEFORE INSERT ON TRANSACTION FOR EACH ROW
BEGIN
:NEW.TRX_ID := TRX_GENERATE();
END;