---GENERATES ACCOUNT_ID WHEN AN ACCOUNT IS CREATED. THIS FUNCTION IS CALLED WHEN THE TRIGGER FOR ACCOUNT TABLE IS FIRED

create or replace FUNCTION generate_acc_id
RETURN NUMBER
IS
ID NUMBER;
BEGIN
SELECT MAX(ACC_NO) INTO ID FROM ACCOUNT;
IF ID IS NULL THEN
  ID := TO_NUMBER('1110001');
ELSE
  ID := ID + 1;
END IF;
RETURN ID;
END;