---ALL TRANSACTION FUNCTION
---TO RETRIVE THE TRANSACTION HISTORY FOR A SPECIFIC ACCOUNT

create or replace FUNCTION all_transaction (p_account IN NUMBER) 
RETURN SYS_REFCURSOR 
AS 
my_cursor SYS_REFCURSOR; 
BEGIN 
OPEN my_cursor FOR SELECT TRX_ID, TO_CHAR(TRX_DATE,'DD-MM-YYYY') as TRX_DATE, TRX_TIME, AMOUNT, TRX_TYPE, TRX_ACCOUNT FROM TRANSACTION
WHERE acc_no = p_account 
ORDER BY TRX_ID; 
RETURN my_cursor; 
END; 
