---RETRIEVES HASHCODE FROM THE REMOTE DATABASE

create or replace FUNCTION HASHRETRIEVE (TRXACC_NUMBER IN NUMBER, TRXAMOUNT IN NUMBER)
RETURN NUMBER
IS
CODE NUMBER;
BEGIN
SELECT HASHCODE INTO CODE FROM HASHTABLE
WHERE ACC_NO = TRXACC_NUMBER AND AMOUNT = TRXAMOUNT;
RETURN CODE;
EXCEPTION
WHEN NO_DATA_FOUND THEN
CODE := -1;
RETURN CODE;
END;