---GENERATE THE TRANSACTION ID FOR A TRANSACTION. THIS FUNCTION IS CALLED WHEN THE TRIGGER FOR INSERT EVENT OF TRANSACTION TABLE IS FIRED

create or replace FUNCTION TRX_GENERATE
RETURN NUMBER 
IS
ID number;
BEGIN
SELECT MAX(TRX_ID) INTO ID FROM TRANSACTION;
IF ID IS NULL THEN
ID := 100001;
ELSE 
ID := ID + 1;
END IF;
RETURN ID;
END;